name    'zleslie-freebsd'
version '0.0.1'
source 'git://github.com/xaque208/puppet-freebsd.git'
author 'zleslie'
license 'Apache License Version 2.0'
summary 'Manage parts of FreeBSD'
description 'A Puppet module to manage various aspects of FreeBSD'
project_page 'https://github.com/xaque208/puppet-freebsd'
dependency 'csail/shell_config'
